### ISSUE TITLE
Use automated builds

### ISSUE THREAD

**Issue by J0WI** [jumanjihouse/docker-ssllabs-scan#18]
See https://docs.docker.com/docker-hub/builds/

**Comment by jumanjiman** [comment]
@J0WI  thank you for the suggestion!

iiuic, automated builds cannot handle the build-and-test harness of this repo.

for example, let's pretend i want to run a test harness to ensure the built image runs as intended.
with automated builds, i have to include all the tests and binaries inside the built image in order to test it. 

for this image, the runtime is `FROM scratch`. that means i cannot run any sort of test harness to confirm the image actually built correctly.

would it help to include in the readme a section about how the builds are performed hands-free by circleci?

example:

### Build integrity

The repo is set up to compile the software in a "builder" container, then copy the statically-compiled binary into a "runtime" container free of development tools or other binaries that could be abused. An unattended test harness runs the build script and runs acceptance tests. If all tests pass on master branch in the unattended test harness, it pushes the built images to the Docker hub.

![docker_hub_workflow](https://cloud.githubusercontent.com/assets/332496/12213107/ac5163b6-b640-11e5-86f6-1869e9c5e507.png)
